// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A platform-agnostic configuration for Firebase initialization.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions has not been configured for platform '
          '${defaultTargetPlatform.toString().split('.').last}.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTHvp-t9PwthjIK1Qs9ajCCSp95_phOw',
    appId: '1:570647069916:android:f28544a0cbbf7df9732019',
    messagingSenderId: '570647069916',
    projectId: 'cuisinemenu-b9009',
    storageBucket: 'cuisinemenu-b9009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoTHvp-t9PwthjIK1Qs9ajCCSp95_phOw',
    appId: '1:570647069916:ios:dummy', // Replace with actual iOS app ID
    messagingSenderId: '570647069916',
    projectId: 'cuisinemenu-b9009',
    storageBucket: 'cuisinemenu-b9009.firebasestorage.app',
    iosBundleId: 'com.example.cuisineMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoTHvp-t9PwthjIK1Qs9ajCCSp95_phOw',
    appId: '1:570647069916:macos:dummy', // Replace with actual macOS app ID
    messagingSenderId: '570647069916',
    projectId: 'cuisinemenu-b9009',
    storageBucket: 'cuisinemenu-b9009.firebasestorage.app',
    iosBundleId: 'com.example.cuisineMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoTHvp-t9PwthjIK1Qs9ajCCSp95_phOw',
    appId: '1:570647069916:windows:dummy', // Replace with actual Windows app ID
    messagingSenderId: '570647069916',
    projectId: 'cuisinemenu-b9009',
    storageBucket: 'cuisinemenu-b9009.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAoTHvp-t9PwthjIK1Qs9ajCCSp95_phOw',
    appId: '1:570647069916:linux:dummy', // Replace with actual Linux app ID
    messagingSenderId: '570647069916',
    projectId: 'cuisinemenu-b9009',
    storageBucket: 'cuisinemenu-b9009.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTHvp-t9PwthjIK1Qs9ajCCSp95_phOw',
    appId: '1:570647069916:web:dummy', // Replace with actual web app ID
    messagingSenderId: '570647069916',
    projectId: 'cuisinemenu-b9009',
    storageBucket: 'cuisinemenu-b9009.firebasestorage.app',
  );
}
